services:
  web:
    build:
      context: web
    volumes:
     - ./web:/app
    ports:
     - "5002:8505"
    networks:
      - postgres
  
  populate_db:
    build:
      context: populate_db
    volumes:
     - ./populate_db:/app
    networks:
      - postgres
  api:
    build:
      context: api
    volumes:
     - ./api:/app
    ports:
     - "5001:5000"
    networks:
      - postgres
  
  postgres:
    container_name: postgres_container_bis
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  
  pgadmin:
    container_name: pgadmin_container_bis
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: matthieu.colombert@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "5005:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: